//// this file was generated by api_gen.py. please DO NOT edit this file directly.
#pragma once

#include "sys.hpp"

namespace cpl {
namespace sys {
namespace api {
namespace Crypt32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        CryptBinaryToStringA CryptBinaryToStringA{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_CryptBinaryToStringA = api::DynamicModule::LoadFunction<::cpl::sys::api::Crypt32::CryptBinaryToStringA>("CryptBinaryToStringA", false);
                if (!ret_CryptBinaryToStringA) {
                } else {
                    any_loaded = true;
                    CryptBinaryToStringA = ret_CryptBinaryToStringA.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            CryptBinaryToStringA = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace AdvAPI32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() = default;
        ConvertStringSecurityDescriptorToSecurityDescriptorA ConvertStringSecurityDescriptorToSecurityDescriptorA{};
        ConvertSidToStringSidA ConvertSidToStringSidA{};
        ConvertStringSidToSidA ConvertStringSidToSidA{};
        RtlGenRandom RtlGenRandom{};
        CryptAcquireContextA CryptAcquireContextA{};
        CryptReleaseContext CryptReleaseContext{};
        CryptGenRandom CryptGenRandom{};
        CryptImportKey CryptImportKey{};
        CryptDestroyKey CryptDestroyKey{};
        CryptSetKeyParam CryptSetKeyParam{};
        CryptEncrypt CryptEncrypt{};
        CryptDecrypt CryptDecrypt{};
        CryptCreateHash CryptCreateHash{};
        CryptDestroyHash CryptDestroyHash{};
        CryptSetHashParam CryptSetHashParam{};
        CryptGetHashParam CryptGetHashParam{};
        CryptHashData CryptHashData{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_ConvertStringSecurityDescriptorToSecurityDescriptorA = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::ConvertStringSecurityDescriptorToSecurityDescriptorA>("ConvertStringSecurityDescriptorToSecurityDescriptorA");
                if (!ret_ConvertStringSecurityDescriptorToSecurityDescriptorA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    ConvertStringSecurityDescriptorToSecurityDescriptorA = ret_ConvertStringSecurityDescriptorToSecurityDescriptorA.value<>();
                }
                const auto ret_ConvertSidToStringSidA = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::ConvertSidToStringSidA>("ConvertSidToStringSidA");
                if (!ret_ConvertSidToStringSidA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    ConvertSidToStringSidA = ret_ConvertSidToStringSidA.value<>();
                }
                const auto ret_ConvertStringSidToSidA = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::ConvertStringSidToSidA>("ConvertStringSidToSidA");
                if (!ret_ConvertStringSidToSidA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    ConvertStringSidToSidA = ret_ConvertStringSidToSidA.value<>();
                }
                const auto ret_RtlGenRandom = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::RtlGenRandom>("RtlGenRandom", false);
                if (!ret_RtlGenRandom) {
                } else {
                    any_loaded = true;
                    RtlGenRandom = ret_RtlGenRandom.value<>();
                }
                const auto ret_CryptAcquireContextA = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptAcquireContextA>("CryptAcquireContextA", false);
                if (!ret_CryptAcquireContextA) {
                } else {
                    any_loaded = true;
                    CryptAcquireContextA = ret_CryptAcquireContextA.value<>();
                }
                const auto ret_CryptReleaseContext = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptReleaseContext>("CryptReleaseContext", false);
                if (!ret_CryptReleaseContext) {
                } else {
                    any_loaded = true;
                    CryptReleaseContext = ret_CryptReleaseContext.value<>();
                }
                const auto ret_CryptGenRandom = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptGenRandom>("CryptGenRandom", false);
                if (!ret_CryptGenRandom) {
                } else {
                    any_loaded = true;
                    CryptGenRandom = ret_CryptGenRandom.value<>();
                }
                const auto ret_CryptImportKey = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptImportKey>("CryptImportKey", false);
                if (!ret_CryptImportKey) {
                } else {
                    any_loaded = true;
                    CryptImportKey = ret_CryptImportKey.value<>();
                }
                const auto ret_CryptDestroyKey = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptDestroyKey>("CryptDestroyKey", false);
                if (!ret_CryptDestroyKey) {
                } else {
                    any_loaded = true;
                    CryptDestroyKey = ret_CryptDestroyKey.value<>();
                }
                const auto ret_CryptSetKeyParam = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptSetKeyParam>("CryptSetKeyParam", false);
                if (!ret_CryptSetKeyParam) {
                } else {
                    any_loaded = true;
                    CryptSetKeyParam = ret_CryptSetKeyParam.value<>();
                }
                const auto ret_CryptEncrypt = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptEncrypt>("CryptEncrypt", false);
                if (!ret_CryptEncrypt) {
                } else {
                    any_loaded = true;
                    CryptEncrypt = ret_CryptEncrypt.value<>();
                }
                const auto ret_CryptDecrypt = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptDecrypt>("CryptDecrypt", false);
                if (!ret_CryptDecrypt) {
                } else {
                    any_loaded = true;
                    CryptDecrypt = ret_CryptDecrypt.value<>();
                }
                const auto ret_CryptCreateHash = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptCreateHash>("CryptCreateHash", false);
                if (!ret_CryptCreateHash) {
                } else {
                    any_loaded = true;
                    CryptCreateHash = ret_CryptCreateHash.value<>();
                }
                const auto ret_CryptDestroyHash = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptDestroyHash>("CryptDestroyHash", false);
                if (!ret_CryptDestroyHash) {
                } else {
                    any_loaded = true;
                    CryptDestroyHash = ret_CryptDestroyHash.value<>();
                }
                const auto ret_CryptSetHashParam = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptSetHashParam>("CryptSetHashParam", false);
                if (!ret_CryptSetHashParam) {
                } else {
                    any_loaded = true;
                    CryptSetHashParam = ret_CryptSetHashParam.value<>();
                }
                const auto ret_CryptGetHashParam = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptGetHashParam>("CryptGetHashParam", false);
                if (!ret_CryptGetHashParam) {
                } else {
                    any_loaded = true;
                    CryptGetHashParam = ret_CryptGetHashParam.value<>();
                }
                const auto ret_CryptHashData = api::DynamicModule::LoadFunction<::cpl::sys::api::AdvAPI32::CryptHashData>("CryptHashData", false);
                if (!ret_CryptHashData) {
                } else {
                    any_loaded = true;
                    CryptHashData = ret_CryptHashData.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return Err(cpl::Error(cpl::Error::UnavailableAPI, "load module or function failed"));
        }

        Int32Result Unload() override {
            ConvertStringSecurityDescriptorToSecurityDescriptorA = nullptr;
            ConvertSidToStringSidA = nullptr;
            ConvertStringSidToSidA = nullptr;
            RtlGenRandom = nullptr;
            CryptAcquireContextA = nullptr;
            CryptReleaseContext = nullptr;
            CryptGenRandom = nullptr;
            CryptImportKey = nullptr;
            CryptDestroyKey = nullptr;
            CryptSetKeyParam = nullptr;
            CryptEncrypt = nullptr;
            CryptDecrypt = nullptr;
            CryptCreateHash = nullptr;
            CryptDestroyHash = nullptr;
            CryptSetHashParam = nullptr;
            CryptGetHashParam = nullptr;
            CryptHashData = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace bcrypt {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        BCryptGenRandom BCryptGenRandom{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_BCryptGenRandom = api::DynamicModule::LoadFunction<::cpl::sys::api::bcrypt::BCryptGenRandom>("BCryptGenRandom", false);
                if (!ret_BCryptGenRandom) {
                } else {
                    any_loaded = true;
                    BCryptGenRandom = ret_BCryptGenRandom.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            BCryptGenRandom = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace Ws2_32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        WSAStartup WSAStartup{};
        WSACleanup WSACleanup{};
        WSAGetLastError WSAGetLastError{};
        socket socket{};
        htons htons{};
        inet_addr inet_addr{};
        sendto sendto{};
        closesocket closesocket{};
        setsockopt setsockopt{};
        bind bind{};
        recvfrom recvfrom{};
        ntohs ntohs{};
        ioctlsocket ioctlsocket{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_WSAStartup = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::WSAStartup>("WSAStartup");
                if (!ret_WSAStartup) {
                    ok = false;
                } else {
                    any_loaded = true;
                    WSAStartup = ret_WSAStartup.value<>();
                }
                const auto ret_WSACleanup = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::WSACleanup>("WSACleanup");
                if (!ret_WSACleanup) {
                    ok = false;
                } else {
                    any_loaded = true;
                    WSACleanup = ret_WSACleanup.value<>();
                }
                const auto ret_WSAGetLastError = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::WSAGetLastError>("WSAGetLastError");
                if (!ret_WSAGetLastError) {
                    ok = false;
                } else {
                    any_loaded = true;
                    WSAGetLastError = ret_WSAGetLastError.value<>();
                }
                const auto ret_socket = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::socket>("socket");
                if (!ret_socket) {
                    ok = false;
                } else {
                    any_loaded = true;
                    socket = ret_socket.value<>();
                }
                const auto ret_htons = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::htons>("htons");
                if (!ret_htons) {
                    ok = false;
                } else {
                    any_loaded = true;
                    htons = ret_htons.value<>();
                }
                const auto ret_inet_addr = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::inet_addr>("inet_addr");
                if (!ret_inet_addr) {
                    ok = false;
                } else {
                    any_loaded = true;
                    inet_addr = ret_inet_addr.value<>();
                }
                const auto ret_sendto = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::sendto>("sendto");
                if (!ret_sendto) {
                    ok = false;
                } else {
                    any_loaded = true;
                    sendto = ret_sendto.value<>();
                }
                const auto ret_closesocket = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::closesocket>("closesocket");
                if (!ret_closesocket) {
                    ok = false;
                } else {
                    any_loaded = true;
                    closesocket = ret_closesocket.value<>();
                }
                const auto ret_setsockopt = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::setsockopt>("setsockopt");
                if (!ret_setsockopt) {
                    ok = false;
                } else {
                    any_loaded = true;
                    setsockopt = ret_setsockopt.value<>();
                }
                const auto ret_bind = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::bind>("bind");
                if (!ret_bind) {
                    ok = false;
                } else {
                    any_loaded = true;
                    bind = ret_bind.value<>();
                }
                const auto ret_recvfrom = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::recvfrom>("recvfrom");
                if (!ret_recvfrom) {
                    ok = false;
                } else {
                    any_loaded = true;
                    recvfrom = ret_recvfrom.value<>();
                }
                const auto ret_ntohs = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::ntohs>("ntohs");
                if (!ret_ntohs) {
                    ok = false;
                } else {
                    any_loaded = true;
                    ntohs = ret_ntohs.value<>();
                }
                const auto ret_ioctlsocket = api::DynamicModule::LoadFunction<::cpl::sys::api::Ws2_32::ioctlsocket>("ioctlsocket");
                if (!ret_ioctlsocket) {
                    ok = false;
                } else {
                    any_loaded = true;
                    ioctlsocket = ret_ioctlsocket.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            WSAStartup = nullptr;
            WSACleanup = nullptr;
            WSAGetLastError = nullptr;
            socket = nullptr;
            htons = nullptr;
            inet_addr = nullptr;
            sendto = nullptr;
            closesocket = nullptr;
            setsockopt = nullptr;
            bind = nullptr;
            recvfrom = nullptr;
            ntohs = nullptr;
            ioctlsocket = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace WinINet {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() = default;
        InternetOpenA InternetOpenA{};
        InternetConnectA InternetConnectA{};
        HttpOpenRequestA HttpOpenRequestA{};
        HttpSendRequestA HttpSendRequestA{};
        InternetReadFile InternetReadFile{};
        InternetCloseHandle InternetCloseHandle{};
        InternetCrackUrlA InternetCrackUrlA{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_InternetOpenA = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::InternetOpenA>("InternetOpenA");
                if (!ret_InternetOpenA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    InternetOpenA = ret_InternetOpenA.value<>();
                }
                const auto ret_InternetConnectA = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::InternetConnectA>("InternetConnectA");
                if (!ret_InternetConnectA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    InternetConnectA = ret_InternetConnectA.value<>();
                }
                const auto ret_HttpOpenRequestA = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::HttpOpenRequestA>("HttpOpenRequestA");
                if (!ret_HttpOpenRequestA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    HttpOpenRequestA = ret_HttpOpenRequestA.value<>();
                }
                const auto ret_HttpSendRequestA = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::HttpSendRequestA>("HttpSendRequestA");
                if (!ret_HttpSendRequestA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    HttpSendRequestA = ret_HttpSendRequestA.value<>();
                }
                const auto ret_InternetReadFile = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::InternetReadFile>("InternetReadFile");
                if (!ret_InternetReadFile) {
                    ok = false;
                } else {
                    any_loaded = true;
                    InternetReadFile = ret_InternetReadFile.value<>();
                }
                const auto ret_InternetCloseHandle = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::InternetCloseHandle>("InternetCloseHandle");
                if (!ret_InternetCloseHandle) {
                    ok = false;
                } else {
                    any_loaded = true;
                    InternetCloseHandle = ret_InternetCloseHandle.value<>();
                }
                const auto ret_InternetCrackUrlA = api::DynamicModule::LoadFunction<::cpl::sys::api::WinINet::InternetCrackUrlA>("InternetCrackUrlA");
                if (!ret_InternetCrackUrlA) {
                    ok = false;
                } else {
                    any_loaded = true;
                    InternetCrackUrlA = ret_InternetCrackUrlA.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return Err(cpl::Error(cpl::Error::UnavailableAPI, "load module or function failed"));
        }

        Int32Result Unload() override {
            InternetOpenA = nullptr;
            InternetConnectA = nullptr;
            HttpOpenRequestA = nullptr;
            HttpSendRequestA = nullptr;
            InternetReadFile = nullptr;
            InternetCloseHandle = nullptr;
            InternetCrackUrlA = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace IPv4 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        GetAdaptersInfo GetAdaptersInfo{};
        GetAdaptersAddresses GetAdaptersAddresses{};
        GetIpForwardTable GetIpForwardTable{};
        DeleteIpForwardEntry DeleteIpForwardEntry{};
        CreateIpForwardEntry CreateIpForwardEntry{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_GetAdaptersInfo = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv4::GetAdaptersInfo>("GetAdaptersInfo");
                if (!ret_GetAdaptersInfo) {
                    ok = false;
                } else {
                    any_loaded = true;
                    GetAdaptersInfo = ret_GetAdaptersInfo.value<>();
                }
                const auto ret_GetAdaptersAddresses = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv4::GetAdaptersAddresses>("GetAdaptersAddresses");
                if (!ret_GetAdaptersAddresses) {
                    ok = false;
                } else {
                    any_loaded = true;
                    GetAdaptersAddresses = ret_GetAdaptersAddresses.value<>();
                }
                const auto ret_GetIpForwardTable = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv4::GetIpForwardTable>("GetIpForwardTable");
                if (!ret_GetIpForwardTable) {
                    ok = false;
                } else {
                    any_loaded = true;
                    GetIpForwardTable = ret_GetIpForwardTable.value<>();
                }
                const auto ret_DeleteIpForwardEntry = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv4::DeleteIpForwardEntry>("DeleteIpForwardEntry");
                if (!ret_DeleteIpForwardEntry) {
                    ok = false;
                } else {
                    any_loaded = true;
                    DeleteIpForwardEntry = ret_DeleteIpForwardEntry.value<>();
                }
                const auto ret_CreateIpForwardEntry = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv4::CreateIpForwardEntry>("CreateIpForwardEntry");
                if (!ret_CreateIpForwardEntry) {
                    ok = false;
                } else {
                    any_loaded = true;
                    CreateIpForwardEntry = ret_CreateIpForwardEntry.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            GetAdaptersInfo = nullptr;
            GetAdaptersAddresses = nullptr;
            GetIpForwardTable = nullptr;
            DeleteIpForwardEntry = nullptr;
            CreateIpForwardEntry = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace IPv6 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        GetIpForwardTable2 GetIpForwardTable2{};
        DeleteIpForwardEntry2 DeleteIpForwardEntry2{};
        FreeMibTable FreeMibTable{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_GetIpForwardTable2 = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv6::GetIpForwardTable2>("GetIpForwardTable2", false);
                if (!ret_GetIpForwardTable2) {
                } else {
                    any_loaded = true;
                    GetIpForwardTable2 = ret_GetIpForwardTable2.value<>();
                }
                const auto ret_DeleteIpForwardEntry2 = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv6::DeleteIpForwardEntry2>("DeleteIpForwardEntry2", false);
                if (!ret_DeleteIpForwardEntry2) {
                } else {
                    any_loaded = true;
                    DeleteIpForwardEntry2 = ret_DeleteIpForwardEntry2.value<>();
                }
                const auto ret_FreeMibTable = api::DynamicModule::LoadFunction<::cpl::sys::api::IPv6::FreeMibTable>("FreeMibTable", false);
                if (!ret_FreeMibTable) {
                } else {
                    any_loaded = true;
                    FreeMibTable = ret_FreeMibTable.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            GetIpForwardTable2 = nullptr;
            DeleteIpForwardEntry2 = nullptr;
            FreeMibTable = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace PsAPI {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        GetModuleFileNameExA GetModuleFileNameExA{};
        EnumProcesses EnumProcesses{};
        EnumProcessModules EnumProcessModules{};
        EnumProcessModulesEx EnumProcessModulesEx{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_GetModuleFileNameExA = api::DynamicModule::LoadFunction<::cpl::sys::api::PsAPI::GetModuleFileNameExA>("GetModuleFileNameExA", false);
                if (!ret_GetModuleFileNameExA) {
                } else {
                    any_loaded = true;
                    GetModuleFileNameExA = ret_GetModuleFileNameExA.value<>();
                }
                const auto ret_EnumProcesses = api::DynamicModule::LoadFunction<::cpl::sys::api::PsAPI::EnumProcesses>("EnumProcesses", false);
                if (!ret_EnumProcesses) {
                } else {
                    any_loaded = true;
                    EnumProcesses = ret_EnumProcesses.value<>();
                }
                const auto ret_EnumProcessModules = api::DynamicModule::LoadFunction<::cpl::sys::api::PsAPI::EnumProcessModules>("EnumProcessModules", false);
                if (!ret_EnumProcessModules) {
                } else {
                    any_loaded = true;
                    EnumProcessModules = ret_EnumProcessModules.value<>();
                }
                const auto ret_EnumProcessModulesEx = api::DynamicModule::LoadFunction<::cpl::sys::api::PsAPI::EnumProcessModulesEx>("EnumProcessModulesEx", false);
                if (!ret_EnumProcessModulesEx) {
                } else {
                    any_loaded = true;
                    EnumProcessModulesEx = ret_EnumProcessModulesEx.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            GetModuleFileNameExA = nullptr;
            EnumProcesses = nullptr;
            EnumProcessModules = nullptr;
            EnumProcessModulesEx = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace NtDLL {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() = default;
        NtSuspendProcess NtSuspendProcess{};
        NtResumeProcess NtResumeProcess{};
        NtTerminateProcess NtTerminateProcess{};
        NtQueryInformationProcess NtQueryInformationProcess{};
        RtlGetVersion RtlGetVersion{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_NtSuspendProcess = api::DynamicModule::LoadFunction<::cpl::sys::api::NtDLL::NtSuspendProcess>("NtSuspendProcess");
                if (!ret_NtSuspendProcess) {
                    ok = false;
                } else {
                    any_loaded = true;
                    NtSuspendProcess = ret_NtSuspendProcess.value<>();
                }
                const auto ret_NtResumeProcess = api::DynamicModule::LoadFunction<::cpl::sys::api::NtDLL::NtResumeProcess>("NtResumeProcess");
                if (!ret_NtResumeProcess) {
                    ok = false;
                } else {
                    any_loaded = true;
                    NtResumeProcess = ret_NtResumeProcess.value<>();
                }
                const auto ret_NtTerminateProcess = api::DynamicModule::LoadFunction<::cpl::sys::api::NtDLL::NtTerminateProcess>("NtTerminateProcess");
                if (!ret_NtTerminateProcess) {
                    ok = false;
                } else {
                    any_loaded = true;
                    NtTerminateProcess = ret_NtTerminateProcess.value<>();
                }
                const auto ret_NtQueryInformationProcess = api::DynamicModule::LoadFunction<::cpl::sys::api::NtDLL::NtQueryInformationProcess>("NtQueryInformationProcess");
                if (!ret_NtQueryInformationProcess) {
                    ok = false;
                } else {
                    any_loaded = true;
                    NtQueryInformationProcess = ret_NtQueryInformationProcess.value<>();
                }
                const auto ret_RtlGetVersion = api::DynamicModule::LoadFunction<::cpl::sys::api::NtDLL::RtlGetVersion>("RtlGetVersion");
                if (!ret_RtlGetVersion) {
                    ok = false;
                } else {
                    any_loaded = true;
                    RtlGetVersion = ret_RtlGetVersion.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return Err(cpl::Error(cpl::Error::UnavailableAPI, "load module or function failed"));
        }

        Int32Result Unload() override {
            NtSuspendProcess = nullptr;
            NtResumeProcess = nullptr;
            NtTerminateProcess = nullptr;
            NtQueryInformationProcess = nullptr;
            RtlGetVersion = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace UserEnv {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        CreateEnvironmentBlock CreateEnvironmentBlock{};
        DestroyEnvironmentBlock DestroyEnvironmentBlock{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_CreateEnvironmentBlock = api::DynamicModule::LoadFunction<::cpl::sys::api::UserEnv::CreateEnvironmentBlock>("CreateEnvironmentBlock", false);
                if (!ret_CreateEnvironmentBlock) {
                } else {
                    any_loaded = true;
                    CreateEnvironmentBlock = ret_CreateEnvironmentBlock.value<>();
                }
                const auto ret_DestroyEnvironmentBlock = api::DynamicModule::LoadFunction<::cpl::sys::api::UserEnv::DestroyEnvironmentBlock>("DestroyEnvironmentBlock", false);
                if (!ret_DestroyEnvironmentBlock) {
                } else {
                    any_loaded = true;
                    DestroyEnvironmentBlock = ret_DestroyEnvironmentBlock.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            CreateEnvironmentBlock = nullptr;
            DestroyEnvironmentBlock = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace Kernel32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() = default;
        ProcessIdToSessionId ProcessIdToSessionId{};
        WTSGetActiveConsoleSessionId WTSGetActiveConsoleSessionId{};
        QueryFullProcessImageNameA QueryFullProcessImageNameA{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_ProcessIdToSessionId = api::DynamicModule::LoadFunction<::cpl::sys::api::Kernel32::ProcessIdToSessionId>("ProcessIdToSessionId", false);
                if (!ret_ProcessIdToSessionId) {
                } else {
                    any_loaded = true;
                    ProcessIdToSessionId = ret_ProcessIdToSessionId.value<>();
                }
                const auto ret_WTSGetActiveConsoleSessionId = api::DynamicModule::LoadFunction<::cpl::sys::api::Kernel32::WTSGetActiveConsoleSessionId>("WTSGetActiveConsoleSessionId", false);
                if (!ret_WTSGetActiveConsoleSessionId) {
                } else {
                    any_loaded = true;
                    WTSGetActiveConsoleSessionId = ret_WTSGetActiveConsoleSessionId.value<>();
                }
                const auto ret_QueryFullProcessImageNameA = api::DynamicModule::LoadFunction<::cpl::sys::api::Kernel32::QueryFullProcessImageNameA>("QueryFullProcessImageNameA", false);
                if (!ret_QueryFullProcessImageNameA) {
                } else {
                    any_loaded = true;
                    QueryFullProcessImageNameA = ret_QueryFullProcessImageNameA.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return Err(cpl::Error(cpl::Error::UnavailableAPI, "load module or function failed"));
        }

        Int32Result Unload() override {
            ProcessIdToSessionId = nullptr;
            WTSGetActiveConsoleSessionId = nullptr;
            QueryFullProcessImageNameA = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace User32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        SendMessageTimeoutA SendMessageTimeoutA{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_SendMessageTimeoutA = api::DynamicModule::LoadFunction<::cpl::sys::api::User32::SendMessageTimeoutA>("SendMessageTimeoutA", false);
                if (!ret_SendMessageTimeoutA) {
                } else {
                    any_loaded = true;
                    SendMessageTimeoutA = ret_SendMessageTimeoutA.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            SendMessageTimeoutA = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace WtsAPI32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}
        WTSQueryUserToken WTSQueryUserToken{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_WTSQueryUserToken = api::DynamicModule::LoadFunction<::cpl::sys::api::WtsAPI32::WTSQueryUserToken>("WTSQueryUserToken", false);
                if (!ret_WTSQueryUserToken) {
                } else {
                    any_loaded = true;
                    WTSQueryUserToken = ret_WTSQueryUserToken.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            WTSQueryUserToken = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace MsImg32 {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() = default;
        GradientFill GradientFill{};

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                const auto ret_GradientFill = api::DynamicModule::LoadFunction<::cpl::sys::api::MsImg32::GradientFill>("GradientFill");
                if (!ret_GradientFill) {
                    ok = false;
                } else {
                    any_loaded = true;
                    GradientFill = ret_GradientFill.value<>();
                }
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return Err(cpl::Error(cpl::Error::UnavailableAPI, "load module or function failed"));
        }

        Int32Result Unload() override {
            GradientFill = nullptr;
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}

namespace OpenSSL {
    class DynamicModule final : public api::DynamicModule {
    public:
        explicit DynamicModule() : api::DynamicModule(false) {}

        Int32Result Load() override {
            for (const auto& dll : DLL_NAMES) {
                (void)api::DynamicModule::Unload();
                api::DynamicModule::szDllName = dll;
                const auto loadRet = api::DynamicModule::Load();
                if (!loadRet) {
                    continue;
                }
                bool ok = true;
                bool any_loaded = false;
                if (ok && (any_loaded || DLL_NAMES.size() == 1)) {
                    return 0;
                }
            }
            return 0;
        }

        Int32Result Unload() override {
            const auto unloadRet = api::DynamicModule::Unload();
            if (!unloadRet) {
                return unloadRet;
            }
            return 0;
        }
    };
}






class API final: public base::ISingleton<API> {
    friend class base::ISingleton<API>;
    API() = default;
    bool loaded{false};
public:
    Crypt32::DynamicModule Crypt32{};
    AdvAPI32::DynamicModule AdvAPI32{};
    bcrypt::DynamicModule bcrypt{};
    Ws2_32::DynamicModule Ws2_32{};
    WinINet::DynamicModule WinINet{};
    IPv4::DynamicModule IPv4{};
    IPv6::DynamicModule IPv6{};
    PsAPI::DynamicModule PsAPI{};
    NtDLL::DynamicModule NtDLL{};
    UserEnv::DynamicModule UserEnv{};
    Kernel32::DynamicModule Kernel32{};
    User32::DynamicModule User32{};
    WtsAPI32::DynamicModule WtsAPI32{};
    MsImg32::DynamicModule MsImg32{};
    OpenSSL::DynamicModule OpenSSL{};

    Int32Result Load() {
        if (!this->loaded) {
            this->loaded = true;
                const auto ret_Crypt32 = this->Crypt32.Load();
            if (!ret_Crypt32) {
                return ret_Crypt32;
            }
            const auto ret_AdvAPI32 = this->AdvAPI32.Load();
            if (!ret_AdvAPI32) {
                return ret_AdvAPI32;
            }
            const auto ret_bcrypt = this->bcrypt.Load();
            if (!ret_bcrypt) {
                return ret_bcrypt;
            }
            const auto ret_Ws2_32 = this->Ws2_32.Load();
            if (!ret_Ws2_32) {
                return ret_Ws2_32;
            }
            const auto ret_WinINet = this->WinINet.Load();
            if (!ret_WinINet) {
                return ret_WinINet;
            }
            const auto ret_IPv4 = this->IPv4.Load();
            if (!ret_IPv4) {
                return ret_IPv4;
            }
            const auto ret_IPv6 = this->IPv6.Load();
            if (!ret_IPv6) {
                return ret_IPv6;
            }
            const auto ret_PsAPI = this->PsAPI.Load();
            if (!ret_PsAPI) {
                return ret_PsAPI;
            }
            const auto ret_NtDLL = this->NtDLL.Load();
            if (!ret_NtDLL) {
                return ret_NtDLL;
            }
            const auto ret_UserEnv = this->UserEnv.Load();
            if (!ret_UserEnv) {
                return ret_UserEnv;
            }
            const auto ret_Kernel32 = this->Kernel32.Load();
            if (!ret_Kernel32) {
                return ret_Kernel32;
            }
            const auto ret_User32 = this->User32.Load();
            if (!ret_User32) {
                return ret_User32;
            }
            const auto ret_WtsAPI32 = this->WtsAPI32.Load();
            if (!ret_WtsAPI32) {
                return ret_WtsAPI32;
            }
            const auto ret_MsImg32 = this->MsImg32.Load();
            if (!ret_MsImg32) {
                return ret_MsImg32;
            }
            const auto ret_OpenSSL = this->OpenSSL.Load();
            if (!ret_OpenSSL) {
                return ret_OpenSSL;
            }
            return 0;
        }
        return 0;
    }
};



} // namespace api
} // namespace sys
} // namespace cpl
